# Generated by Django 5.2.17 on 2026-09-15 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('TRAIN', 'Training'), ('TEST', 'Testing'), ('RAW', 'Raw audience')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='predictor.company')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ANALYST', 'Analyst')], default='OWNER', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='predictor.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('actual_churn', models.IntegerField(blank=True, null=True)),
                ('actual_action', models.CharField(blank=True, max_length=40)),
                ('actual_ltv', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='predictor.company')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=30)),
                ('rows', models.IntegerField()),
                ('churn_accuracy', models.FloatField(null=True)),
                ('churn_precision', models.FloatField(null=True)),
                ('churn_recall', models.FloatField(null=True)),
                ('churn_f1', models.FloatField(null=True)),
                ('churn_auc', models.FloatField(null=True)),
                ('action_accuracy', models.FloatField(null=True)),
                ('ltv_r2', models.FloatField(null=True)),
                ('segments', models.IntegerField(default=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='predictor.company')),
            ],
        ),
        migrations.CreateModel(
            name='UserPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('segment', models.CharField(blank=True, max_length=80)),
                ('churn_probability', models.FloatField(default=0)),
                ('engagement_health', models.FloatField(default=0)),
                ('predicted_ltv', models.FloatField(default=0)),
                ('next_action', models.CharField(blank=True, max_length=40)),
                ('risk', models.CharField(blank=True, max_length=20)),
                ('recommendation', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'user_id'), name='uniq_company_userprediction')],
            },
        ),
    ]
