from pathlib import Path
import pandas as pd,numpy as np,json,joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import *
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
ROOT=Path(__file__).resolve().parents[1];D=ROOT/"data";M=ROOT/"model_artifacts"
F=["sessions_7d","session_change_7d","listening_minutes_7d","listening_change_7d","skip_rate","save_rate","share_rate","playlist_rate","search_rate","discovery_rate","unique_artists_7d","unique_genres_7d","days_active_14d","avg_session_minutes","subscription_age_days","support_tickets_30d","night_listening_share","completion_rate","avg_daily_sessions","weekend_usage_share","session_gap_hours","artist_concentration","genre_concentration","notification_open_rate","recommendation_click_rate","offline_downloads_30d","playlists_created_30d","social_interactions_30d","device_switch_rate","ad_skip_rate","notification_fatigue","content_diversity"]
df=pd.read_csv(D/"users.csv"); fit=df.sample(min(5000,len(df)),random_state=42).copy(); X=fit[F];y=fit.churn;tr,te=train_test_split(np.arange(len(fit)),test_size=.2,stratify=y,random_state=42)
clf=RandomForestClassifier(n_estimators=50,max_depth=10,min_samples_leaf=5,class_weight="balanced",random_state=42,n_jobs=2);clf.fit(X.iloc[tr],y.iloc[tr]);p=clf.predict_proba(X.iloc[te])[:,1];pred=(p>=.5).astype(int)
reg=RandomForestRegressor(n_estimators=50,max_depth=12,min_samples_leaf=5,random_state=42,n_jobs=2);reg.fit(X.iloc[tr],np.log1p(fit.ltv.iloc[tr]));lp=np.expm1(reg.predict(X.iloc[te]));true=fit.ltv.iloc[te]
axtr,axte,aytr,ayte=train_test_split(X,fit.next_action,test_size=.2,stratify=fit.next_action,random_state=42);act=RandomForestClassifier(n_estimators=50,max_depth=10,min_samples_leaf=5,class_weight="balanced",random_state=42,n_jobs=2);act.fit(axtr,aytr);ap=act.predict(axte)
sc=StandardScaler();km=KMeans(n_clusters=6,n_init=10,random_state=42).fit(sc.fit_transform(X));cent=pd.DataFrame(sc.inverse_transform(km.cluster_centers_),columns=F);score=cent.sessions_7d.rank()+cent.listening_minutes_7d.rank()+cent.discovery_rate.rank()+cent.days_active_14d.rank()-cent.skip_rate.rank();order=list(score.sort_values(ascending=False).index);names=["Daily Loyalist","Explorer","Binge Listener","Community Builder","Drifting User","Ghost / Low Activity"];mapping={c:names[j] for j,c in enumerate(order)}
for name,obj in [("churn_model.pkl",{"model":clf,"features":F}),("ltv_model.pkl",{"model":reg,"features":F}),("action_model.pkl",{"model":act,"features":F}),("segment_model.pkl",{"model":km,"scaler":sc,"mapping":mapping,"features":F})]:joblib.dump(obj,M/name)
# score full 15k/25k dataset in batches
allX=df[F];ids=km.predict(sc.transform(allX));df["segment_id"]=ids;df["segment"]=[mapping.get(int(i),"Segment") for i in ids];df["churn_probability"]=clf.predict_proba(allX)[:,1];df["predicted_ltv"]=np.expm1(reg.predict(allX));df["predicted_next_action"]=act.predict(allX);df["engagement_health"]=(1-df.churn_probability).clip(0,1)*100;df["risk"]=np.where(df.churn_probability>=.72,"CRITICAL",np.where(df.churn_probability>=.5,"HIGH",np.where(df.churn_probability>=.25,"MODERATE","LOW")))
q=df.predicted_ltv.quantile(.75)
def rec(r):
 if r.churn_probability>=.72 and r.predicted_ltv>=q:return "Priority retention: personalized re-engagement for a high-value at-risk user"
 if r.skip_rate>.55 or r.ad_skip_rate>.65:return "Improve first-result matching and reduce skip-heavy sessions"
 if r.discovery_rate<.25 or r.content_diversity<.30:return "Increase discovery and broaden personalized content exposure"
 if r.sessions_7d<3 or r.session_change_7d<-.25:return "Re-engage with a lightweight personalized entry point"
 if r.notification_fatigue>.65:return "Reduce notification pressure and optimize message timing"
 return "Maintain experience and grow engagement"
df["recommendation"]=[rec(r) for r in df.itertuples()];df.to_csv(D/"audience_predictions.csv",index=False);df[F+["churn","ltv","next_action"]].sample(1200,random_state=42).to_csv(D/"training_template.csv",index=False);df[F+["churn","ltv","next_action"]].sample(600,random_state=7).to_csv(D/"test_template.csv",index=False)
fpr,tpr,_=roc_curve(y.iloc[te],p);pr,rc,_=precision_recall_curve(y.iloc[te],p);rep={"rows":len(df),"training_fit_rows":len(fit),"events":len(pd.read_csv(D/"streaming_events.csv")),"features":F,"feature_count":len(F),"model_type":"Random Forest ensemble","n_estimators":50,"churn_accuracy":float(accuracy_score(y.iloc[te],pred)),"churn_precision":float(precision_score(y.iloc[te],pred,zero_division=0)),"churn_recall":float(recall_score(y.iloc[te],pred,zero_division=0)),"churn_f1":float(f1_score(y.iloc[te],pred,zero_division=0)),"churn_roc_auc":float(roc_auc_score(y.iloc[te],p)),"confusion_matrix":confusion_matrix(y.iloc[te],pred).tolist(),"ltv_mae":float(mean_absolute_error(true,lp)),"ltv_rmse":float(np.sqrt(mean_squared_error(true,lp))),"ltv_r2":float(r2_score(true,lp)),"action_accuracy":float(accuracy_score(ayte,ap)),"segments":6,"feature_importance":dict(sorted(zip(F,clf.feature_importances_),key=lambda x:-x[1])),"segment_counts":df.segment.value_counts().to_dict(),"action_counts":df.next_action.value_counts().to_dict(),"risk_counts":df.risk.value_counts().to_dict(),"roc_curve":{"fpr":fpr[::max(1,len(fpr)//80)].tolist(),"tpr":tpr[::max(1,len(tpr)//80)].tolist()},"pr_curve":{"precision":pr[::max(1,len(pr)//80)].tolist(),"recall":rc[::max(1,len(rc)//80)].tolist()},"generated_at":"2026-09-15","note":"Synthetic streaming-platform audience data for demonstration; not private platform data."};(M/"model_report.json").write_text(json.dumps(rep,indent=2));print(json.dumps({k:rep[k] for k in ["rows","events","feature_count","n_estimators","churn_accuracy","churn_roc_auc","ltv_r2","action_accuracy"]},indent=2))
